id: I84508F97
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:12:26+00:00'
last_modified: '2022-06-07T13:36:52.618934+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11778
  title: གླིང་གེ་སར་རྒྱལ་པོའི་རྟོགས་བརྗོད་ལས་འཁྲུངས་གླིང་མེ་ཏོག་ར་བ་དང་རྟ་རྒྱུག་ནོར་བུ་ཆ་བདུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    168E:
      image_group_id: I1KG11780
      title: ''
      total_pages: 740
      order: 1
      base_file: 168E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
