id: opecha:P000743
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11778
  title: གླིང་གེ་སར་རྒྱལ་པོའི་རྟོགས་བརྗོད་ལས་འཁྲུངས་གླིང་མེ་ཏོག་ར་བ་དང་རྟ་རྒྱུག་ནོར་བུ་ཆ་བདུན།
  volume: ''
  author: ''
