id: P000743
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11778
  title: གླིང་གེ་སར་རྒྱལ་པོའི་རྟོགས་བརྗོད་ལས་འཁྲུངས་གླིང་མེ་ཏོག་ར་བ་དང་རྟ་རྒྱུག་ནོར་བུ་ཆ་བདུན།
  author: ''
  volumes:
    40dcac28fd1a4f6c9cb12375d03fc02b:
      image_group_id: I1KG11780
      title: ''
      volume_number: 1
      total_pages: 740
